<a href="https://colab.research.google.com/github/GAUZ47/Workspace/blob/main/NumPy_Exercises_Uriarte.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy Exercises for Data Analysis

In [ ]:
# 1. Import numpy as np and see the version

import numpy as np
print("Versión de NumPy:", np.__version__)


Versión de NumPy: 1.22.4


In [ ]:
# 2. Create a 1D array of numbers from 0 to 9

arr_1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Arreglo unidimensional:", arr_1d)


Arreglo unidimensional: [0 1 2 3 4 5 6 7 8 9]


In [ ]:
# 3. Create a 3×3 numpy array of all True’s

arr_3x3 = np.full((3, 3), True, dtype=bool)
print("Arreglo de 3x3 con True's:")
print(arr_3x3)


Arreglo de 3x3 con True's:
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
#4. Extract all odd numbers from arr

odd_numbers = arr_1d[arr_1d % 2 != 0]
print("Números impares:", odd_numbers)


Números impares: [1 3 5 7 9]


In [ ]:
#5. Replace all odd numbers in arr with -1

arr_1d[arr_1d % 2 != 0] = -1
print("Arreglo con números impares reemplazados:", arr_1d)


Arreglo con números impares reemplazados: [ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [ ]:
#6. Convert a 1D array to a 2D array with 2 rows

arr_2d = arr_1d.reshape(2, -1)
print("Arreglo bidimensional con 2 filas:")
print(arr_2d)

Arreglo bidimensional con 2 filas:
[[ 0 -1  2 -1  4]
 [-1  6 -1  8 -1]]


In [ ]:
#7. Stack arrays a and b vertically

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
stacked_vertical = np.vstack((a, b))
print("Apilado vertical:")
print(stacked_vertical)


Apilado vertical:
[[1 2 3]
 [4 5 6]]


In [ ]:
#8. Stack the arrays a and b horizontally.

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
stacked_horizontal = np.hstack((a, b))
print("Apilado horizontal:", stacked_horizontal)


Apilado horizontal: [1 2 3 4 5 6]


In [ ]:
#9. Get all items between 5 and 10 from a.

a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
elements_between_5_10 = a[(a >= 5) & (a <= 10)]
print("Elementos entre 5 y 10:", elements_between_5_10)


Elementos entre 5 y 10: [5 6 7 8 9]


In [ ]:
#  10. How to make a python function that handles scalars to work on numpy arrays?
# Hint
# Desired Output:
# a = np.array([5, 7, 9, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1])
# pair_max(a, b)
# #> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

# Vectorizar la función maxx()
vectorized_maxx = np.vectorize(maxx)

# Arreglos de entrada
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

# Aplicar la función vectorizada a los arreglos de entrada
result = vectorized_maxx(a, b)

# Imprimir el resultado
print(result)


[6 7 9 8 9 7 5]


In [ ]:
#  11. Swap columns 1 and 2 in the array arr.
# Hint
# Desired Output:
# [[0 2 1]
#  [3 5 4]
#  [6 8 7]]

arr = np.arange(9).reshape(3, 3)
print("Original:")
print(arr)

# Intercambiar las columnas 1 y 2
arr[:, [1, 2]] = arr[:, [2, 1]]

print("Intercambiadas:")
print(arr)


Original:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Intercambiadas:
[[0 2 1]
 [3 5 4]
 [6 8 7]]


In [ ]:
#  12. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
# Hint
# The desired Output should be like the following one:
#  [[ 8.50061025  9.10531502  6.85867783]
#   [ 9.76262069  9.87717411  7.13466701]
#   [ 7.48966403  8.33409158  6.16808631]
#   [ 7.75010551  9.94535696  5.27373226]
#   [ 8.0850361   5.56165518  7.31244004]]

random_array = np.random.uniform(5, 10, (5, 3))

print(random_array)

[[7.08170538 9.24036253 6.38449119]
 [7.64340255 7.56377938 8.23943061]
 [8.74362754 7.87510177 9.32004261]
 [6.96964892 8.68138739 8.41837315]
 [8.91183301 6.03266299 6.89220051]]
